### ISSUE TITLE
2 energy databus hosting failures

### ISSUE THREAD

**Issue by kurzum** [dbpedia/databus#85]
1:
Hallo beisammen,

https://moss.tools.dbpedia.org/annotate
reagiert mit
There was an exception while trying to navigate to 'annotate' with the exception message 'HTTP 502 error making the query: Bad Gateway'
Carsten 

2: 
Hallo beisammen,
https://energy.databus.dbpedia.org/app/publish-wizard  führt zu „Sorry can’t find that“
Carsten

**Comment by kurzum** [comment]
![Screenshot from 2023-07-12 10-10-49](https://github.com/dbpedia/databus/assets/900758/70ac7ecd-a165-496f-93e7-edb2754b911c)

OEO Class not found in OEM metadata. Maybe it is something small. VOID finds it.

**Comment by holycrab13** [comment]
We need to migrate the energy databus asap and update to the lastest version. That should resolve the second issue.

**Comment by yum-yab** [comment]
Hi, issue 1 is already resolved since the mods sparql endpoint was restartet.

@kurzum Its not clear what the problem with this class is, if its nowhere annotated nothing gets found. Are you sure its in the actual metadata somewhere? Can you pinpoint the metadata/databus identifier it was used in?

here an example of a working query:
![image](https://github.com/dbpedia/databus/assets/37804144/5495110d-6654-44f7-b766-82a8bd97ab3b)

**Comment by kurzum** [comment]
@yum-yab actually this could be a good way to test future versions of MOSS. Could you write a query that lists all classes that should be successfull in retrieving sth via the OEP Metadata search? 
Limit 10 should be enough.

**Comment by holycrab13** [comment]
This is not strictly a 2.1.0 task, should this be moved to migration?
